apiVersion: v2
name: prometheus-stack
description: Prometheus and Grafana Stack
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 46.0.0
    repository: https://prometheus-community.github.io/helm-charts